name: Pipeline de execução K6

on: 
  workflow_dispatch:
    inputs:
      test_file:
        description: 'Arquivo de teste a executar'
        required: true
        default: 'tests/testCi.js'
        type: choice
        options:
          - tests/testCi.js
          - tests/accounts.js
          - tests/pingServer.js
      vu_1:
        description: 'Número de usuários virtuais (VUs) para estágio 1'
        required: false
        default: '100'
        type: string
      duration_1:
        description: 'Duração do teste para estágio 1 (ex: 30s, 1m)'
        required: false
        default: '30s'
        type: string

      vu_2:
        description: 'Número de usuários virtuais (VUs) para estágio 2'
        required: false
        default: '150'
        type: string
      duration_2:
        description: 'Duração do teste para estágio 2 (ex: 30s, 1m)'
        required: false
        default: '50s'
        type: string

      vu_3:
        description: 'Número de usuários virtuais (VUs) para estágio 3'
        required: false
        default: '100'
        type: string
      duration_3:
        description: 'Duração do teste para estágio 3 (ex: 30s, 1m)'
        required: false
        default: '30s'
        type: string
  push:
    branches:
      - master
  
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup K6
      uses: grafana/setup-k6-action@v1

    - name: Run local k6 test
      uses: grafana/run-k6-action@v1
      with:
        path: ${{ github.event.inputs.test_file }}
      env:
        K6_VUS_1: ${{ github.event.inputs.vu_1 }}
        K6_DURATION_1: ${{ github.event.inputs.duration_1 }}
        K6_VUS_2: ${{ github.event.inputs.vu_2 }}
        K6_DURATION_2: ${{ github.event.inputs.duration_2 }}
        K6_VUS_3: ${{ github.event.inputs.vu_3 }}
        K6_DURATION_3: ${{ github.event.inputs.duration_3 }}
    
    - name: Publish HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: k6-execution-logs
        path: logs/
        retention-days: 7
